"""Reviewed, static copy for the complete EN/FR/DE/ES buying journey."""
LANGUAGES = {'en':'English', 'fr':'Français', 'de':'Deutsch', 'es':'Español'}
# Each row: English | French | German | Spanish. No runtime translation service.
ROWS = '''
domains|Domains|Domaines|Domains|Dominios
bundles|Bundles|Lots de domaines|Domain-Pakete|Paquetes de dominios
process|How it works|Comment acheter|So funktioniert es|Cómo comprar
contact|Contact|Contact|Kontakt|Contacto
studio|The studio|Le studio|Das Studio|El estudio
spirit|Our spirit|Notre esprit|Unsere Haltung|Nuestra filosofía
all|All|Tous|Alle|Todos
featured|Selected|Notre sélection|Unsere Auswahl|Nuestra selección
shown|domains shown|domaines affichés|Domains angezeigt|dominios mostrados
view|View details|Voir la fiche|Details ansehen|Ver detalles
market|View price on Afternic|Voir le prix sur Afternic|Preis bei Afternic ansehen|Ver precio en Afternic
offer|Make an offer|Faire une offre|Angebot abgeben|Hacer una oferta
bundle_offer|Enquire about this pair|Demander une offre pour ce lot|Dieses Paket anfragen|Consultar este paquete
back|All domains|Tous les domaines|Alle Domains|Todos los dominios
skip|Skip to content|Aller au contenu|Zum Inhalt|Ir al contenido
menu|Open menu|Ouvrir le menu|Menü öffnen|Abrir menú
close|Close menu|Fermer le menu|Menü schließen|Cerrar menú
language|Language|Langue|Sprache|Idioma
hero|Find a name worth building on.|Un nom pour donner vie à votre projet.|Ein Name, auf dem Ihre Idee aufbauen kann.|Un nombre para dar vida a tu proyecto.
intro|Explore domain names for AI, digital trust, payments and fragrance. Discover their potential uses and choose your acquisition route.|Découvrez des domaines pour l’IA, la confiance numérique, les paiements et la parfumerie. Explorez leurs usages et les modalités d’acquisition.|Entdecken Sie Domains für KI, digitales Vertrauen, Zahlungen und Parfümerie. Erkunden Sie mögliche Anwendungen und den passenden Kaufweg.|Descubre dominios para IA, confianza digital, pagos y perfumería. Explora sus posibles usos y las opciones de compra.
explore|Explore domains|Découvrir les domaines|Domains entdecken|Explorar dominios
catalog|The portfolio|Le portefeuille|Das Portfolio|El catálogo
catalog_title|Your next name starts here.|Votre prochain nom est ici.|Hier beginnt Ihr nächster Name.|Tu próximo nombre empieza aquí.
catalog_intro|One collection, clear uses. Open a domain to explore the concept and naming considerations.|Une sélection, des usages clairs. Consultez chaque fiche pour découvrir le concept et les particularités du nom.|Eine Auswahl mit klaren Einsatzmöglichkeiten. Jede Detailseite erläutert das Konzept und die Besonderheiten des Namens.|Una selección con usos claros. Cada ficha explica el concepto y las particularidades del nombre.
why|Why this name|Pourquoi ce nom|Warum dieser Name|Por qué este nombre
concept|What you could build|Ce que vous pourriez créer|Was Sie damit aufbauen könnten|Qué podrías crear
tradeoff|What to consider|À prendre en compte|Was zu beachten ist|Qué debes tener en cuenta
buyers|Who it could suit|À qui ce nom peut convenir|Für wen der Name geeignet ist|A quién puede encajarle
only|Domain name only|Nom de domaine uniquement|Nur der Domainname|Solo el nombre de dominio
boundary|These are possible business concepts. No website, software, traffic, customers or trademark rights are included unless separately agreed in writing.|Ces concepts sont des pistes de création. Aucun site, logiciel, trafic, client ou droit de marque n’est inclus, sauf accord écrit distinct.|Die Konzepte sind mögliche Geschäftsideen. Websites, Software, Traffic, Kunden oder Markenrechte sind nur bei gesonderter schriftlicher Vereinbarung enthalten.|Estos conceptos son ideas de negocio posibles. No se incluyen sitios web, software, tráfico, clientes ni derechos de marca salvo acuerdo escrito independiente.
market_note|The link opens Afternic. Confirm the current price, availability and transfer terms there. MzunguWay is not an official marketplace partner.|Le lien ouvre Afternic. Vérifiez le prix, la disponibilité et les conditions de transfert sur la plateforme. MzunguWay n’en est pas un partenaire officiel.|Der Link führt zu Afternic. Prüfen Sie dort Preis, Verfügbarkeit und Übertragungsbedingungen. MzunguWay ist kein offizieller Partner des Marktplatzes.|El enlace abre Afternic. Confirma allí el precio, la disponibilidad y las condiciones de transferencia. MzunguWay no es socio oficial de la plataforma.
private_note|Private enquiry: availability, price, payment method and transfer terms must be agreed before payment.|Demande privée : disponibilité, prix, moyen de paiement et conditions de transfert à convenir avant tout paiement.|Private Anfrage: Verfügbarkeit, Preis, Zahlungsweise und Übertragungsbedingungen sind vor der Zahlung zu vereinbaren.|Consulta privada: deben acordarse disponibilidad, precio, forma de pago y condiciones de transferencia antes de pagar.
bundle_title|Connected names. A shared direction.|Des noms complémentaires, une même direction.|Passende Namen. Eine gemeinsame Richtung.|Nombres complementarios. Una misma dirección.
bundle_note|Each pair is available for enquiry. We confirm both domains, combined terms and the transfer process before an agreement. No package discount is implied; individual enquiries are welcome.|Chaque paire peut faire l’objet d’une demande. Disponibilité, conditions globales et transfert sont confirmés avant accord. Aucune remise n’est présumée ; les demandes individuelles restent possibles.|Jedes Paar kann angefragt werden. Verfügbarkeit, Gesamtbedingungen und Übertragung werden vor einer Vereinbarung bestätigt. Ein Paketrabatt ist nicht zugesagt; Einzelanfragen sind willkommen.|Puedes consultar cada pareja. La disponibilidad, las condiciones conjuntas y la transferencia se confirman antes del acuerdo. No se presupone un descuento; también se aceptan consultas individuales.
process_title|From a name to ownership.|Du choix du nom à son acquisition.|Vom Namen zum Eigentum.|Del nombre a su adquisición.
step1|Choose your domain and review its intended use.|Choisissez un domaine et examinez ses usages possibles.|Wählen Sie eine Domain und prüfen Sie die möglichen Anwendungen.|Elige un dominio y revisa sus posibles usos.
step2|Check the marketplace price or send a private offer.|Consultez le prix sur la plateforme ou formulez une offre privée.|Prüfen Sie den Marktplatzpreis oder geben Sie ein privates Angebot ab.|Consulta el precio en la plataforma o presenta una oferta privada.
step3|Agree the payment and transfer terms before proceeding.|Confirmez les modalités de paiement et de transfert avant de poursuivre.|Vereinbaren Sie Zahlungs- und Übertragungsbedingungen, bevor Sie fortfahren.|Acuerda las condiciones de pago y transferencia antes de continuar.
step4|Complete the transfer, then connect your new domain to your project.|Finalisez le transfert, puis reliez le domaine à votre projet.|Schließen Sie die Übertragung ab und verbinden Sie die Domain mit Ihrem Projekt.|Completa la transferencia y conecta el dominio con tu proyecto.
faq|Buying questions|Questions sur l’achat|Fragen zum Kauf|Preguntas sobre la compra
qprice|Where is the price?|Où consulter le prix ?|Wo finde ich den Preis?|¿Dónde puedo ver el precio?
aprice|Prices are shown on the linked marketplace when available. For privately offered names and bundles, request the current terms.|Les prix figurent sur la plateforme indiquée, lorsqu’un lien est disponible. Pour les domaines proposés en privé et les lots, demandez les conditions actuelles.|Preise finden Sie auf dem verlinkten Marktplatz, sofern vorhanden. Für privat angebotene Domains und Pakete fragen Sie die aktuellen Konditionen an.|Los precios aparecen en la plataforma enlazada, cuando está disponible. Para dominios privados y paquetes, solicita las condiciones actuales.
qinclude|What is included?|Qu’est-ce qui est inclus ?|Was ist enthalten?|¿Qué incluye la compra?
qtime|How long does transfer take?|Combien de temps prend le transfert ?|Wie lange dauert die Übertragung?|¿Cuánto tarda la transferencia?
atime|Timing depends on the registrar, domain status and transaction provider. Confirm any transfer lock or account-push option before paying.|Le délai dépend du registrar, du statut du domaine et du prestataire de transaction. Vérifiez les éventuels blocages de transfert ou possibilités de changement de compte avant paiement.|Die Dauer hängt vom Registrar, Domainstatus und Transaktionsanbieter ab. Prüfen Sie mögliche Transfersperren oder einen Kontowechsel vor der Zahlung.|El plazo depende del registrador, del estado del dominio y del proveedor de la transacción. Confirma posibles bloqueos de transferencia o cambios de cuenta antes de pagar.
qbundle|Can I buy a pair?|Puis-je acheter une paire ?|Kann ich ein Paket kaufen?|¿Puedo comprar una pareja?
studio_text|We explore business ideas, select names with a clear purpose and explain who they could serve. Our role is to connect a domain with a project that can make it useful.|Nous explorons des idées d’activité, sélectionnons des noms à l’usage clair et expliquons à qui ils peuvent servir. Notre rôle : rapprocher un domaine d’un projet capable de lui donner vie.|Wir erkunden Geschäftsideen, wählen Namen mit klarem Zweck und erläutern, für wen sie nützlich sein können. Wir verbinden Domains mit Projekten, die daraus etwas machen können.|Exploramos ideas de negocio, seleccionamos nombres con un propósito claro y explicamos a quién pueden servir. Conectamos dominios con proyectos capaces de darles vida.
spirit_title|Beyond familiar borders.|Au-delà des frontières familières.|Über vertraute Grenzen hinaus.|Más allá de las fronteras conocidas.
spirit_text|MzunguWay draws inspiration from movement, discovery and a nod to Kiswahili and East Africa. We approach unfamiliar fields with questions, listen before assuming and connect ideas across languages and industries. A name is an invitation; what comes next belongs to its builder.|MzunguWay s’inspire du mouvement et de la découverte, avec un clin d’œil au kiswahili et à l’Afrique de l’Est. Nous abordons les univers nouveaux avec des questions, écoutons avant de supposer et relions les idées entre langues et secteurs. Un nom est une invitation ; la suite appartient à celui qui construit.|MzunguWay ist von Bewegung und Entdeckung inspiriert, mit einem Bezug zu Kiswahili und Ostafrika. Wir begegnen unbekannten Bereichen mit Fragen, hören zu, bevor wir urteilen, und verbinden Ideen über Sprachen und Branchen hinweg. Ein Name ist eine Einladung; was daraus wird, liegt bei denen, die darauf aufbauen.|MzunguWay se inspira en el movimiento y el descubrimiento, con un guiño al suajili y a África Oriental. Nos acercamos a lo desconocido con preguntas, escuchamos antes de asumir y conectamos ideas entre idiomas y sectores. Un nombre es una invitación; lo que venga después pertenece a quien lo desarrolle.
form_title|Let’s discuss your domain.|Parlons de votre domaine.|Sprechen wir über Ihre Domain.|Hablemos de tu dominio.
form_intro|Prepare your enquiry below, then send it through your email app. You can also copy the message and write to hello@mzunguway.com.|Préparez votre demande ci-dessous, puis envoyez-la depuis votre messagerie. Vous pouvez aussi copier le message et écrire à hello@mzunguway.com.|Bereiten Sie Ihre Anfrage vor und senden Sie sie anschließend über Ihr E-Mail-Programm. Alternativ können Sie den Text kopieren und an hello@mzunguway.com schreiben.|Prepara tu consulta y envíala desde tu aplicación de correo. También puedes copiar el mensaje y escribir a hello@mzunguway.com.
domain_label|Domain or bundle|Domaine ou lot|Domain oder Paket|Dominio o paquete
email|Your email|Votre email|Ihre E-Mail-Adresse|Tu correo electrónico
budget|Offer and currency (optional)|Offre et devise (facultatif)|Angebot und Währung (optional)|Oferta y moneda (opcional)
message|Your message|Votre message|Ihre Nachricht|Tu mensaje
prepare|Prepare email|Préparer l’email|E-Mail vorbereiten|Preparar correo
send|Open my email app|Ouvrir ma messagerie|E-Mail-Programm öffnen|Abrir mi correo
copy|Copy message|Copier le message|Nachricht kopieren|Copiar mensaje
ready|Your message is ready. It has not been sent. Open your email app to send it, or copy the text below.|Votre message est prêt. Il n’a pas été envoyé. Ouvrez votre messagerie pour l’envoyer, ou copiez le texte ci-dessous.|Ihre Nachricht ist fertig. Sie wurde noch nicht gesendet. Öffnen Sie Ihr E-Mail-Programm oder kopieren Sie den Text unten.|Tu mensaje está listo. Todavía no se ha enviado. Abre tu correo para enviarlo o copia el texto siguiente.
copied|Message copied.|Message copié.|Nachricht kopiert.|Mensaje copiado.
copy_fail|Select and copy the message below.|Sélectionnez et copiez le message ci-dessous.|Markieren und kopieren Sie die Nachricht unten.|Selecciona y copia el mensaje siguiente.
privacy|This form prepares a message on your device. Nothing is sent until you send the email. We use enquiries to respond to acquisition requests.|Ce formulaire prépare un message sur votre appareil. Rien n’est transmis avant l’envoi de votre email. Les demandes servent à répondre aux projets d’acquisition.|Dieses Formular bereitet eine Nachricht auf Ihrem Gerät vor. Erst beim E-Mail-Versand werden Angaben übermittelt. Anfragen dienen der Bearbeitung Ihres Kaufinteresses.|Este formulario prepara un mensaje en tu dispositivo. No se envía nada hasta que envíes el correo. Las consultas se utilizan para responder a solicitudes de compra.
nojs|You can contact us directly by email if this form is unavailable.|Si le formulaire est indisponible, contactez-nous directement par email.|Falls das Formular nicht verfügbar ist, kontaktieren Sie uns direkt per E-Mail.|Si el formulario no está disponible, escríbenos directamente por correo.
rights|All rights reserved.|Tous droits réservés.|Alle Rechte vorbehalten.|Todos los derechos reservados.
collections|Collections|Collections|Kollektionen|Colecciones
pair_pay|Agent payments|Paiements des agents|Agentenzahlungen|Pagos de agentes
pair_security|AI agent security|Sécurité des agents IA|Sicherheit von KI-Agenten|Seguridad de agentes de IA
pair_voice|Arabic voice|Voix arabe|Arabische Sprachtechnologie|Tecnología de voz árabe
pair_trust|Synthetic media and voice trust|Confiance dans les médias synthétiques et la voix|Vertrauen in synthetische Medien und Sprache|Confianza en medios sintéticos y voz
pay_desc|Identity and authorization alongside transaction risk review.|L’identité et l’autorisation, associées à l’analyse du risque transactionnel.|Identität und Autorisierung, ergänzt durch die Prüfung von Transaktionsrisiken.|Identidad y autorización junto al análisis del riesgo de transacciones.
security_desc|A security hub paired with a specialist prompt-injection resource.|Un portail de sécurité associé à une ressource spécialisée en injection de prompt.|Ein Sicherheitsportal mit einer spezialisierten Ressource zu Prompt Injection.|Un portal de seguridad junto a un recurso especializado en inyección de prompts.
voice_desc|A commercial voice-agent platform and a speech experimentation space.|Une plateforme commerciale d’agents vocaux et un espace d’expérimentation de la parole.|Eine kommerzielle Sprachagenten-Plattform und ein Experimentierraum für Sprachtechnologie.|Una plataforma comercial de agentes de voz y un espacio de experimentación del habla.
trust_desc|Complementary resources for synthetic-media incidents and voice scams.|Des ressources complémentaires sur les incidents liés aux médias synthétiques et les fraudes vocales.|Ergänzende Ressourcen zu Vorfällen mit synthetischen Medien und Sprachbetrug.|Recursos complementarios sobre incidentes con medios sintéticos y fraudes de voz.
'''
UI = {l:{} for l in LANGUAGES}
for row in ROWS.strip().splitlines():
    key,*values=row.split('|')
    assert len(values)==4, key
    for l,v in zip(LANGUAGES,values): UI[l][key]=v
CATEGORIES = {
'Voice & Fraud':['Voice & Fraud','Voix et fraude','Sprache und Betrug','Voz y fraude'],
'Responsible AI':['Responsible AI','IA responsable','Verantwortungsvolle KI','IA responsable'],
'Fragrance & Commerce':['Fragrance & Commerce','Parfumerie et commerce','Parfümerie und Handel','Perfumería y comercio'],
'AI Security': ['AI Security','Sécurité IA','KI-Sicherheit','Seguridad de IA'],
'Voice & AI': ['Voice & AI','Voix et IA','Sprache und KI','Voz e IA'],
'AI Visibility':['AI Visibility','Visibilité IA','KI-Sichtbarkeit','Visibilidad en IA'],
'Trust & Safety':['Trust & Safety','Confiance et protection','Vertrauen und Schutz','Confianza y protección'],
'Governance':['Governance','Gouvernance','Governance','Gobernanza'],
'Fragrance':['Fragrance','Parfumerie','Parfümerie','Perfumería'],
'Agent Payments':['Agent Payments','Paiements des agents','Agentenzahlungen','Pagos de agentes'],
}
# Per domain: tagline, possible concept, naming rationale, trade-off, intended buyers.
COPY = {'fr':{}, 'de':{}, 'es':{}}
DOMAIN_ROWS = {
'fr': '''
agentsecurity.help|Un point d’entrée clair pour sécuriser les agents IA.|Un portail de conseils, de vérification des permissions et de documentation des incidents, rattaché à une offre de cybersécurité.|Le sujet est explicite et l’extension .help exprime une vocation d’assistance. Le nom couvre plusieurs besoins : accès aux outils, intégrations et réponse aux incidents.|Le périmètre est large. Pour un produit consacré uniquement à l’injection de prompt, un nom plus spécialisé peut convenir davantage.|Éditeurs de cybersécurité, plateformes d’agents, équipes de sécurité et prestataires de services managés.
arabicvoiceagent.com|Un nom explicite pour les agents vocaux en arabe.|Une plateforme qui relie un agent vocal arabophone à la téléphonie, au CRM et aux réservations, avec des règles de transfert vers un conseiller humain.|Le nom indique la langue, l’interface et la catégorie du produit. Le .com convient à une offre commerciale spécialisée.|Le nom est long et centré sur une langue. La qualité vocale et la couverture des dialectes doivent être démontrées par le produit.|Centres de contact, banques, cliniques, hôtels et éditeurs de solutions conversationnelles.
arabicvoice.xyz|Un espace pour explorer les possibilités de la voix arabe.|Un laboratoire permettant de comparer transcription, synthèse vocale, accents, qualité et latence, puis de tester des intégrations API.|Arabic voice peut accueillir plusieurs usages de la parole, au-delà des agents et des centres de contact. Deux mots réunissent démonstrations et outils créatifs.|L’extension .xyz doit être clairement communiquée. Elle peut moins convenir à un acheteur exigeant un .com pour son offre principale.|Laboratoires vocaux, développeurs, créateurs et plateformes de modèles de voix.
citationreadiness.com|Votre contenu est-il prêt à être cité par l’IA ?|Un service d’audit de contenu : sources, entités, structure, fraîcheur et données structurées, avec un plan d’amélioration priorisé.|Readiness désigne une préparation que le client peut faire évaluer. Le nom peut porter un service d’agence ou le logiciel qui l’accompagne.|Citation peut aussi évoquer le monde académique. Le positionnement doit préciser la recherche IA ; aucun score ne garantit des citations ou un classement.|Agences SEO et GEO, éditeurs, équipes marketing et plateformes de visibilité IA.
deepfakes.help|Face à un deepfake présumé, savoir quoi faire.|Un portail guidant la conservation des preuves, la vérification, les signalements et l’orientation vers des spécialistes compétents.|Le risque est identifiable et .help annonce une ressource d’assistance. Le nom peut servir à l’information comme à l’accompagnement des victimes.|La confiance dépend du service réel. L’analyse d’authenticité doit expliquer ses limites et ne pas promettre une détection infaillible.|Acteurs de cybersécurité, médias, assureurs, associations et équipes de protection des utilisateurs.
promptinjection.help|Des conseils pratiques contre l’injection de prompt.|Un centre de ressources défensives : frontières de confiance, accès aux outils, exemples de tests sûrs et guides de réduction des risques.|Le nom correspond à un problème technique précis. Il peut compléter un produit de sécurité par une documentation spécialisée.|Le sujet est technique et ciblé. Il convient moins à une marque généraliste ; les recommandations doivent suivre l’évolution des attaques.|Développeurs, éditeurs de cybersécurité, équipes de tests et plateformes d’agents.
responsibleagents.org|Un espace commun pour des agents IA responsables.|Une initiative publiant recherches, principes de gouvernance, modèles de politiques et retours d’expérience sur le déploiement des agents.|Le pluriel permet de réunir plusieurs disciplines. Le .org correspond à une initiative collective ou d’intérêt général.|Le domaine ne confère aucune autorité normative ni certification. La crédibilité repose sur les contributeurs et la méthode.|Chercheurs, associations, équipes de gouvernance et consortiums sectoriels.
voicefraud.help|Vérifier avant de faire confiance à une voix.|Un espace de sensibilisation aux arnaques vocales : vérification indépendante, conservation des preuves et orientation vers le bon canal de signalement.|Le nom relie un risque compréhensible à une promesse d’assistance. Il peut compléter les ressources clients d’une banque ou d’un opérateur.|La prévention ne vaut pas détection automatique. Le service doit préciser son rôle et les limites de son assistance.|Banques, opérateurs télécoms, assureurs et services de prévention de la fraude.
perfum.world|Un univers de senteurs à découvrir.|Une sélection éditoriale de parfums, de familles olfactives et de créateurs, pouvant évoluer vers un service d’échantillons ou une boutique spécialisée.|World ouvre la voie à un univers de découverte. Le nom peut réunir récits de parfumeurs, conseils et sélection de produits.|Perfum est une graphie distinctive, différente de parfum et perfume. Elle exige une identité visuelle cohérente et des liens explicites.|Boutiques de niche, créateurs de contenus olfactifs, parfumeurs et services d’échantillons.
agentpaymentid.com|Une identité claire pour chaque paiement d’agent.|Une couche logicielle reliant l’agent à son mandant, à ses autorisations de dépense et à une trace d’autorisation avant transmission au prestataire de paiement.|Le nom identifie une fonction concrète de l’infrastructure de paiement. Il peut désigner un produit spécialisé ou une API.|ID peut recouvrir plusieurs interprétations. Le positionnement doit préciser l’identité de l’agent et l’autorité déléguée, sans suggérer un agrément de paiement.|Plateformes de paiement, fournisseurs d’identité, outils fintech et startups du commerce par agents.
agentpaymentrisk.com|Un nom dédié au risque des paiements d’agents.|Un outil examinant le contexte d’une transaction, les politiques de dépense et les exceptions, avec une validation humaine lorsque nécessaire.|Les trois termes précisent le sujet et la fonction. Le nom convient à un module de contrôle ou à une offre autonome d’analyse du risque.|C’est un nom descriptif long, spécialisé dans les agents. La performance de contrôle et les obligations applicables relèvent du produit réel.|Éditeurs de gestion du risque, plateformes de paiement, fintechs et équipes de conformité opérationnelle.
''',
'de': '''
agentsecurity.help|Eine klare Anlaufstelle für sichere KI-Agenten.|Ein Portal für Berechtigungsprüfungen, Sicherheitsleitfäden und Vorfalldokumentation als Ergänzung zu einem Cybersicherheitsangebot.|Der Name nennt das Thema; .help betont die Unterstützung. Werkzeugzugriffe, Integrationen und Vorfälle passen unter dieselbe Adresse.|Das Thema ist breit. Ein ausschließlich auf Prompt Injection spezialisiertes Produkt könnte von einem engeren Namen profitieren.|Sicherheitsanbieter, Agentenplattformen, Sicherheitsteams und Managed-Service-Anbieter.
arabicvoiceagent.com|Ein eindeutiger Name für arabische Sprachagenten.|Eine Plattform verbindet arabischsprachige Agenten mit Telefonie, CRM und Buchungssystemen und regelt die Übergabe an menschliche Mitarbeitende.|Sprache, Schnittstelle und Produktkategorie stehen im Namen. Die .com-Endung passt zu einem spezialisierten kommerziellen Angebot.|Der Name ist lang und sprachspezifisch. Sprachqualität und Dialektabdeckung müssen durch das Produkt belegt werden.|Kontaktzentren, Banken, Kliniken, Hotels und Anbieter von Dialogsystemen.
arabicvoice.xyz|Ein Raum für die Möglichkeiten arabischer Sprache.|Ein Labor zum Vergleich von Transkription, Sprachsynthese, Akzenten, Qualität und Latenz sowie zum Testen von API-Integrationen.|Arabic voice umfasst mehr als Agenten oder Kontaktzentren. Der kurze Wortstamm kann Demos, Sprachmodelle und kreative Werkzeuge vereinen.|Die Endung .xyz muss klar kommuniziert werden. Käufer, die für ihr Hauptangebot eine .com-Adresse benötigen, sollten dies berücksichtigen.|Sprachlabore, Entwickler, Kreative und Plattformen für Sprachmodelle.
citationreadiness.com|Sind Ihre Inhalte bereit, von KI zitiert zu werden?|Ein Inhaltsaudit prüft Quellen, Entitäten, Struktur, Aktualität und strukturierte Daten und liefert einen priorisierten Verbesserungsplan.|Readiness beschreibt eine prüfbare Vorbereitung. Der Name eignet sich für eine wiederholbare Agenturleistung oder die zugehörige Software.|Citation hat auch akademische Bedeutungen. Die Positionierung sollte KI-Suche nennen; kein Score garantiert Zitate oder Rankings.|SEO- und GEO-Agenturen, Verlage, Marketingteams und Plattformen für KI-Sichtbarkeit.
deepfakes.help|Bei einem vermuteten Deepfake den nächsten Schritt kennen.|Ein Portal unterstützt Beweissicherung, Überprüfung und Meldung und verweist bei Bedarf an geeignete Fachleute.|Das Risiko ist erkennbar und .help signalisiert Unterstützung. Der Name eignet sich für Aufklärung und die Begleitung Betroffener.|Vertrauen muss durch die tatsächliche Leistung entstehen. Echtheitsprüfungen müssen Grenzen offenlegen und dürfen keine fehlerfreie Erkennung versprechen.|Cybersicherheitsanbieter, Medien, Versicherer, Verbände und Teams zum Nutzerschutz.
promptinjection.help|Praktische Hilfe gegen Prompt Injection.|Eine defensive Wissensbasis zu Vertrauensgrenzen, Werkzeugzugriffen, sicheren Tests und Maßnahmen zur Risikominderung.|Der Name entspricht einem konkreten technischen Problem. Er kann ein Sicherheitsprodukt durch spezialisierte Dokumentation ergänzen.|Das Thema ist eng und technisch. Für eine allgemeine Marke ist es weniger geeignet; Leitfäden müssen mit neuen Angriffen Schritt halten.|Entwickler, Sicherheitsanbieter, Testteams und Agentenplattformen.
responsibleagents.org|Ein gemeinsamer Ort für verantwortungsvolle KI-Agenten.|Eine Initiative veröffentlicht Forschung, Governance-Grundsätze, Richtlinienvorlagen und Erfahrungen mit dem Einsatz von Agenten.|Der Plural lässt Raum für mehrere Disziplinen. Die .org-Endung passt zu einer gemeinschaftlichen oder gemeinwohlorientierten Initiative.|Die Domain verleiht keine Normungsbefugnis oder Zertifizierung. Glaubwürdigkeit hängt von Mitwirkenden und Methoden ab.|Forschende, Verbände, Governance-Teams und Branchenkonsortien.
voicefraud.help|Erst prüfen, dann einer Stimme vertrauen.|Eine Anlaufstelle zur Aufklärung über Sprachbetrug: unabhängige Überprüfung, Beweissicherung und Hinweise auf geeignete Meldestellen.|Der Name verbindet ein verständliches Risiko mit Unterstützung. Er kann die Kundeninformationen einer Bank oder eines Telekommunikationsanbieters ergänzen.|Prävention ist keine automatische Erkennung. Das Angebot muss seine Rolle und die Grenzen der Unterstützung benennen.|Banken, Telekommunikationsanbieter, Versicherer und Betrugspräventionsdienste.
perfum.world|Eine Welt der Düfte entdecken.|Eine redaktionelle Auswahl von Düften, Duftfamilien und Herstellern, die zu einem Probenservice oder einem spezialisierten Shop wachsen könnte.|World eröffnet einen Entdeckungsraum. Der Name kann Geschichten von Parfümeuren, Beratung und Produktauswahl verbinden.|Perfum ist eine eigenständige Schreibweise, anders als parfum oder perfume. Sie braucht einen konsistenten Markenauftritt und eindeutige Links.|Nischenhändler, Duftredaktionen, Parfümeure und Probenservices.
agentpaymentid.com|Eine klare Identität für jede Agentenzahlung.|Eine Softwareschicht verknüpft den Agenten mit seinem Auftraggeber, Ausgabenrechten und einem Autorisierungsnachweis vor der Weiterleitung an den Zahlungsanbieter.|Der Name beschreibt eine konkrete Funktion der Zahlungsinfrastruktur. Er passt zu einem spezialisierten Produkt oder einer API.|ID ist mehrdeutig. Die Positionierung sollte Agentenidentität und delegierte Befugnisse erklären, ohne eine Zahlungszulassung anzudeuten.|Zahlungsplattformen, Identitätsanbieter, Fintech-Werkzeuge und Startups für agentengestützten Handel.
agentpaymentrisk.com|Ein gezielter Name für Risiken bei Agentenzahlungen.|Ein Werkzeug prüft Transaktionskontext, Ausgabenrichtlinien und Ausnahmen und fordert bei Bedarf menschliche Freigaben an.|Die drei Begriffe benennen Thema und Funktion. Der Name passt zu einem Kontrollmodul oder einer eigenständigen Risikoanalyse.|Der beschreibende Name ist lang und auf Agenten spezialisiert. Kontrollleistung und geltende Pflichten hängen vom tatsächlichen Produkt ab.|Risikoanbieter, Zahlungsplattformen, Fintechs und operative Compliance-Teams.
''',
'es': '''
agentsecurity.help|Un punto de referencia para agentes de IA más seguros.|Un portal de revisión de permisos, guías de seguridad y documentación de incidentes, vinculado a una oferta de ciberseguridad.|El tema es explícito y .help comunica asistencia. Acceso a herramientas, integraciones e incidentes caben bajo una misma dirección.|El alcance es amplio. Un producto dedicado solo a la inyección de prompts podría beneficiarse de un nombre más específico.|Proveedores de ciberseguridad, plataformas de agentes, equipos de seguridad y servicios gestionados.
arabicvoiceagent.com|Un nombre explícito para agentes de voz en árabe.|Una plataforma conecta agentes de voz en árabe con telefonía, CRM y reservas, con reglas para transferir la conversación a una persona.|El nombre identifica idioma, interfaz y categoría de producto. La extensión .com encaja con una oferta comercial especializada.|Es largo y específico de un idioma. La calidad de voz y la cobertura de dialectos deben demostrarse en el producto.|Centros de contacto, bancos, clínicas, hoteles y proveedores de soluciones conversacionales.
arabicvoice.xyz|Un espacio para explorar las posibilidades de la voz árabe.|Un laboratorio compara transcripción, síntesis, acentos, calidad y latencia, y permite probar integraciones API.|Arabic voice abarca más que agentes o centros de contacto. Dos palabras pueden reunir demostraciones, modelos y herramientas creativas.|La extensión .xyz debe comunicarse claramente. Puede no encajar con un comprador que necesite un .com para su oferta principal.|Laboratorios de voz, desarrolladores, creadores y plataformas de modelos de voz.
citationreadiness.com|¿Está tu contenido preparado para ser citado por la IA?|Una auditoría revisa fuentes, entidades, estructura, actualización y datos estructurados, y entrega un plan de mejoras priorizado.|Readiness plantea una preparación que el cliente puede evaluar. El nombre puede identificar un servicio de agencia o su software.|Citation también tiene significados académicos. Debe aclararse el enfoque en búsquedas con IA; ninguna puntuación garantiza citas ni posiciones.|Agencias SEO y GEO, editoriales, equipos de marketing y plataformas de visibilidad en IA.
deepfakes.help|Saber qué hacer ante un posible deepfake.|Un portal orienta sobre conservación de pruebas, verificación y denuncias, y deriva los casos a especialistas adecuados.|El riesgo es reconocible y .help anuncia asistencia. El nombre puede servir tanto para informar como para apoyar a las víctimas.|La confianza depende del servicio real. La evaluación de autenticidad debe explicar sus límites y no prometer una detección infalible.|Proveedores de ciberseguridad, medios, aseguradoras, asociaciones y equipos de protección de usuarios.
promptinjection.help|Orientación práctica contra la inyección de prompts.|Un centro de recursos defensivos sobre límites de confianza, acceso a herramientas, pruebas seguras y mitigación de riesgos.|El nombre corresponde a un problema técnico concreto. Puede complementar un producto de seguridad con documentación especializada.|Es un tema técnico y específico. Encaja menos con una marca generalista; las recomendaciones deben actualizarse con las amenazas.|Desarrolladores, proveedores de seguridad, equipos de pruebas y plataformas de agentes.
responsibleagents.org|Un espacio común para agentes de IA responsables.|Una iniciativa publica investigaciones, principios de gobernanza, modelos de políticas y experiencias de despliegue de agentes.|El plural permite reunir varias disciplinas. La extensión .org encaja con una iniciativa colectiva o de interés público.|El dominio no otorga autoridad normativa ni certificación. La credibilidad depende de los participantes y del método.|Investigadores, asociaciones, equipos de gobernanza y consorcios sectoriales.
voicefraud.help|Verificar antes de confiar en una voz.|Un espacio educativo sobre estafas de voz: verificación independiente, conservación de pruebas y orientación hacia canales de denuncia.|El nombre conecta un riesgo comprensible con asistencia. Puede complementar los recursos para clientes de bancos u operadores.|La prevención no equivale a detección automática. El servicio debe aclarar su función y sus límites.|Bancos, operadores de telecomunicaciones, aseguradoras y servicios de prevención del fraude.
perfum.world|Un mundo de aromas por descubrir.|Una selección editorial de perfumes, familias olfativas y creadores, con posibilidad de desarrollar un servicio de muestras o una tienda especializada.|World abre un universo de descubrimiento. El nombre puede reunir historias de perfumistas, consejos y selección de productos.|Perfum es una grafía distintiva, diferente de parfum y perfume. Requiere una identidad visual coherente y enlaces claros.|Tiendas de nicho, creadores de contenido sobre fragancias, perfumistas y servicios de muestras.
agentpaymentid.com|Una identidad clara para cada pago de un agente.|Una capa de software vincula al agente con su representado, sus permisos de gasto y un registro de autorización antes de remitir la solicitud al proveedor de pagos.|El nombre identifica una función concreta de la infraestructura de pagos. Puede representar un producto especializado o una API.|ID admite varias interpretaciones. Deben precisarse la identidad del agente y la autoridad delegada sin sugerir una licencia de pagos.|Plataformas de pagos, proveedores de identidad, herramientas fintech y startups de comercio mediante agentes.
agentpaymentrisk.com|Un nombre centrado en el riesgo de pagos de agentes.|Una herramienta revisa el contexto de la transacción, las políticas de gasto y las excepciones, con aprobación humana cuando sea necesaria.|Los tres términos delimitan el tema y la función. Encaja con un módulo de control o una oferta independiente de análisis del riesgo.|Es un nombre descriptivo largo y especializado en agentes. El rendimiento del control y las obligaciones aplicables dependen del producto real.|Proveedores de gestión del riesgo, plataformas de pagos, fintechs y equipos de cumplimiento operativo.
'''}
for lang,rows in DOMAIN_ROWS.items():
    for row in rows.strip().splitlines():
        name,*fields=row.split('|')
        assert len(fields)==5, name
        COPY[lang][name]=dict(zip(('tagline','concept','why','tradeoff','buyers'),fields))
